### ISSUE TITLE
datetime.strptime() throws ValueError

### ISSUE THREAD

**Issue by danoscarmike** [danoscarmike/waqi-python#5]
```
client = core.WaqiClient()
s = client.list_stations_by_keyword('california')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/danom/pycode/waqi-python/waqi_python/core.py", line 66, in list_stations_by_keyword
    for station in stations]
  File "/Users/danom/pycode/waqi-python/waqi_python/core.py", line 66, in <listcomp>
    for station in stations]
  File "/Users/danom/pycode/waqi-python/waqi_python/core.py", line 15, in get_station_by_city_name

    return Station(r.json()['data'])
  File "/Users/danom/pycode/waqi-python/waqi_python/station.py", line 25, in __init__
    # tz = data['time']['tz'].replace(':','')
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data ' -0800' does not match format '%Y-%m-%d %H:%M:%S %z'
```

**Comment by danoscarmike** [comment]
Maybe use `dateutil` instead of `datetime.datetime`?
